# -*- coding: utf-8 -*-
"""test_003_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3XTVXW4QGAtGOGm6JIZ-qm6vaqGheIM
"""

import pandas as pd
import streamlit as st
from fuzzywuzzy import process

# Chargement du DataFrame
df = pd.read_csv('df_streamlit.csv')

# Création de la liste de films
list_movies = list(df["primaryTitle"])

# Fonction pour trouver le meilleur match de film
def trouver_titre_film(entree_utilisateur, liste_film):
    meilleur_match = process.extractOne(entree_utilisateur, liste_film)
    return meilleur_match[0]

# Fonction de recommandation
def recommander_films(titre_film):
    # Trouver l'index du film correspondant
    index_film = df[df['primaryTitle'] == titre_film].index[0]
    # Récupérer les films recommandés
    films_recommandes = df.iloc[index_film][['film1', 'film2', 'film3', 'film4', 'film5']]
    return films_recommandes.tolist()

# Interface utilisateur Streamlit
st.title("Recommandation de Films")

# Saisie de l'utilisateur
entree_utilisateur = st.text_input("Entrez le titre d'un film:")

if entree_utilisateur:
    # Trouver le titre du film le plus proche
    titre_corrige = trouver_titre_film(entree_utilisateur, list_movies)

    # Afficher le titre corrigé
    st.write(f"Titre corrigé: {titre_corrige}")

    # Obtenir des recommandations
    recommandations = recommander_films(titre_corrige)

    # Afficher les recommandations
    st.write(f"Films recommandés pour '{titre_corrige}':")
    for film in recommandations:
        st.write(f"- {film}")